# Configuração princal do Plugin
# by emanuelVINI

#
# ___________                     __    .____         ___.  ___.           ____   ________
# \_   _____/___ _____    _______/  |_  |    |    ____\_ |__\_ |__ ___.__. \   \ /   /_   |
# |    __)/ __ \\__  \  /  ___/\   __\ |    |   /  _ \| __ \| __ <   |  |  \   Y   / |   |
# |     \\  ___/ / __ \_\___ \  |  |   |    |__(  <_> ) \_\ \ \_\ \___  |   \     /  |   |
# \___  / \___  >____  /____  > |__|   |_______ \____/|___  /___  / ____|    \___/   |___|
# \/      \/     \/     \/                 \/         \/    \/\/

#Permissões Admin:

# feastlobby.admin.criar: Permissão para usar o /lobbyadmin criar
# feastlobby.admin.editarservidor: Permissão para usar o /lobbyadmin editarservidor
# feastlobby.admin.bypass: Permissão para colocar e tirar blocos no lobby.
# feastlobby.*: Todas permissões do plugin.
# feastlobby.gamemode: Permissão para alterar seu gamemode
# feastlobby.gamemode.other: permissão para alterar o gamemode de outras pessoas

# Permissões Gerais:

# feastlobby.chat: Permissão para falar e usar cores no chat
# feastlobby.bypass.maintenance: Permissão para entrar em manutenção
# feastlobby.bypass.file.id do servidor: Permissão para burlar a fila daquele servidor


# Placeholders:

# %feastlobby_id do servidor%: Retorna Manutenção ou a quantidade online

error fixer:
  #Se você estiver com erros de SQL no plugin, ative essa opção e reinicie seu servidor, depois desligue ele e desative.
  delete_table: false #Essa opção irá deletar a tabela e criar novamente.
  debug: false #Essa opção e recomendada se você tiver problemas com o plugin, reportar ela.

features:
  #Sistema de chat do plugin
  chat:
    enabled: true
    #Suporta placeholders do PAPI
    format: "&7%name%&f: {message}"
  #Configurações de proteção do mundo
  world:
    disable_weather: true #Desabilita a chuva
    disable_grow: true #Desabilita o crescimento de plantações
    disable_block_place_and_break: true #Desabilita colocar blocos e tirar blocos (feastlobby.admin.bypass)
    disable_entity_spawn: true #Desabilita o nascimento de entidades
    disable_pvp: true #Desabilita o PvP no lobby
    disable_block_interact: true #Desabilita interações com blocos
    always_day: true #Deixa o mundo sempre de dia
  #Configurações de proteção do player
  player:
    disable_food: true #A fome sempre ficará cheia.
    disable_damage: true #Desabilitara o dano no lobby
    disable_item drop: true #Desabilita o drop de itens no Lobby
    set_hp_to_min: true # Define a vida para meio coração.
    clear_inventory: true #Limpa o inventário do jogador ao entrar
  #Sistema de fila do plugin
  file:
    enable: true #Habilitar o sistema de fila
    delay: 500 #Em mili segundos da fila atualizar
    enable_chat_message: true #A mensagem da fila será enviada no chat
    enable_actionbar_message: true #A mensagem da fila será enviada na actionbar
    close_inventory_on_join_leave: true #Fechar o inventário quando entrar ou sair da fila

