# Configuração princal do Plugin
# by emanuelVINI

#
# ___________                     __    .____         ___.  ___.           ____   ________
# \_   _____/___ _____    _______/  |_  |    |    ____\_ |__\_ |__ ___.__. \   \ /   /_   |
# |    __)/ __ \\__  \  /  ___/\   __\ |    |   /  _ \| __ \| __ <   |  |  \   Y   / |   |
# |     \\  ___/ / __ \_\___ \  |  |   |    |__(  <_> ) \_\ \ \_\ \___  |   \     /  |   |
# \___  / \___  >____  /____  > |__|   |_______ \____/|___  /___  / ____|    \___/   |___|
# \/      \/     \/     \/                 \/         \/    \/\/

#Permissões Admin:

# feastlobby.admin.criar: Permissão para usar o /lobbyadmin criar
# feastlobby.admin.editarservidor: Permissão para usar o /lobbyadmin editarservidor
# feastlobby.admin.bypass: Permissão para colocar e tirar blocos no lobby.
# feastlobby.*: Todas permissões do plugin.

# Permissões Gerais:

# feastlobby.chat: Permissão para falar e usar cores no chat
# feastlobby.bypass.maintenance: Permissão para entrar em manutenção
# feastlobby.bypass.file.id do servidor: Permissão para burlar a fila daquele servidor

error fixer:
  #Se você estiver com erros de SQL no plugin, ative essa opção e reinicie seu servidor, depois desligue ele e desative.
  delete table: false #Essa opção irá deletar a tabela e criar novamente.
  debug: false #Essa opção e recomendada se você tiver problemas com o plugin, reportar ela.

features:
  #Sistema de chat do plugin
  chat:
    enabled: true
    format: "%luckperms_prefix%%player_name%&f: {message}"
  #Configurações de proteção do mundo
  world:
    disable weather: true #Desabilita a chuva
    disable grow: true #Desabilita o crescimento de plantações
    disable block place and break: true #Desabilita colocar blocos e tirar blocos (feastlobby.admin.bypass)
    disable entity spawn: true #Desabilita o nascimento de entidades
    disable pvp: true #Desabilita o PvP no lobby
    disable block interact: true #Desabilita interações com blocos
  #Configurações de proteção do player
  player:
    disable food: true #A fome sempre ficará cheia.
    disable damage: true #Desabilitara o dano no lobby
    disable item drop: true #Desabilita o drop de itens no Lobby
    set hp to min: true # Define a vida para meio coração.
    clear inventory: true #Limpa o inventário do jogador ao entrar
  #Sistema de fila do plugin
  file:
    enable: true #Habilitar o sistema de fila
    delay: 500 #Em mili segundos da fila atualizar
    enable chat message: true #A mensagem da fila será enviada no chat
    enable actionbar message: true #A mensagem da fila será enviada na actionbar
    close inventory on join leave: true #Fechar o inventário quando entrar ou sair da fila

