name: FeastLobby
version: 1.0-BETA
main: com.emanuelvini.feastlobby.FeastLobby
author: emanuelVINI
permissions:
  feastlobby.admin.criar:
    default: "op"
    description: "Permiss達o para usar o /lobbyadmin criar"
  feastlobby.admin.editarservidor:
    default: "op"
    description: "Permiss達o para usar o /lobbyadmin editarservidor"
  feastlobby.admin.bypass:
    default: "op"
    description: "Permiss達o para colocar e tirar blocos no lobby."
  feastlobby.*:
    default: "op"
    description: "Permiss達o para usar todos comandos do /lobbyadmin e bypasses"
    children:
      - "feastlobby.admin.criar"
      - "feastlobby.admin.editarservidor"
      - "feastlobby.bypass"
